default: com/Gradescope/DoubleQueue/code/ArrayDoubleQueue.java com/Gradescope/DoubleQueue/code/IDoubleQueue.java com/Gradescope/DoubleQueue/code/ListDoubleQueue.java
	javac  com/Gradescope/DoubleQueue/code/ArrayDoubleQueue.java com/Gradescope/DoubleQueue/code/IDoubleQueue.java com/Gradescope/DoubleQueue/code/ListDoubleQueue.java
 
run:  com/Gradescope/DoubleQueue/code/ArrayDoubleQueue.class com/Gradescope/DoubleQueue/code/IDoubleQueue.class com/Gradescope/DoubleQueue/code/ListDoubleQueue.class
	java  com.Gradescope.DoubleQueue.code.ArrayDoubleQueue com.Gradescope.DoubleQueue.code.IDoubleQueue com.Gradescope.DoubleQueue.code.ListDoubleQueue 

clean:
	rm -f com/Gradescope/DoubleQueue/code/*.class


